import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function buildPdfBytes(receipt: any, verifyUrl: string): Uint8Array {
  // Minimal valid PDF with receipt data
  const lines = [
    `APEX NOTARY — CRYPTOGRAPHIC ATTESTATION RECEIPT`,
    ``,
    `Receipt ID:        ${receipt.commit_id}`,
    `Timestamp:         ${receipt.created_at}`,
    `Predicate:         ${receipt.predicate_id}`,
    `Phase:             ${receipt.phase}`,
    `Status:            ${receipt.status}`,
    ``,
    `CRYPTOGRAPHIC PROOF`,
    `─────────────────────────────────────────────`,
    `Commit Hash:       ${receipt.commit_hash}`,
    `Merkle Leaf:       ${receipt.merkle_leaf_hash}`,
    `Merkle Root:       ${receipt.merkle_root || 'N/A'}`,
    `Ed25519 Signature: ${receipt.ed25519_signature || 'N/A'}`,
    `Sequence:          ${receipt.sequence_number || 'N/A'}`,
    ``,
    `ACTION`,
    `─────────────────────────────────────────────`,
    `${receipt.action}`,
    ``,
    `VERIFICATION`,
    `─────────────────────────────────────────────`,
    `Verify this receipt: ${verifyUrl}`,
    ``,
    `This receipt was cryptographically signed using Ed25519`,
    `(RFC 8032) and anchored to a SHA-256 Merkle tree per`,
    `PSI Protocol v1.2 (draft-singh-psi-00).`,
    ``,
    `EU AI Act Compliance: Articles 12, 13, 14`,
    `Algorithm: SHA-256 (FIPS 180-4)`,
    `Signature: Ed25519 (RFC 8032)`,
    ``,
    `Generated by APEX NOTARY — digital-gallows.com`,
  ];

  const textContent = lines.join("\n");

  // Build minimal PDF
  const objects: string[] = [];
  let objCount = 0;
  const offsets: number[] = [];

  const addObj = (content: string) => {
    objCount++;
    objects.push(`${objCount} 0 obj\n${content}\nendobj\n`);
    return objCount;
  };

  // Catalog
  addObj(`<< /Type /Catalog /Pages 2 0 R >>`);
  // Pages
  addObj(`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`);
  // Page
  addObj(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>`);

  // Content stream
  const escapedLines = lines.map(l => l.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)'));
  let streamContent = "BT\n/F1 9 Tf\n";
  let y = 750;
  for (const line of escapedLines) {
    if (y < 50) break;
    streamContent += `1 0 0 1 50 ${y} Tm\n(${line}) Tj\n`;
    y -= 14;
  }
  streamContent += "ET\n";
  const streamBytes = new TextEncoder().encode(streamContent);
  addObj(`<< /Length ${streamBytes.length} >>\nstream\n${streamContent}endstream`);

  // Font
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>`);

  // Build file
  let pdf = "%PDF-1.4\n";
  for (const obj of objects) {
    offsets.push(pdf.length);
    pdf += obj + "\n";
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objCount + 1}\n`;
  pdf += `0000000000 65535 f \n`;
  for (const off of offsets) {
    pdf += `${off.toString().padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objCount + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return new TextEncoder().encode(pdf);
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405, headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }

  try {
    const { receipt_id } = await req.json();
    if (!receipt_id) {
      return new Response(JSON.stringify({ error: "Missing receipt_id" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" }
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const { data, error } = await supabase
      .from("gallows_ledger")
      .select("*")
      .eq("commit_id", receipt_id)
      .single();

    if (error || !data) {
      return new Response(JSON.stringify({ error: "Receipt not found" }), {
        status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" }
      });
    }

    const projectId = supabaseUrl.match(/\/\/([^.]+)/)?.[1] || "";
    const verifyUrl = `https://${projectId}.supabase.co/functions/v1/verify-hash?hash=${data.commit_hash}`;

    const pdfBytes = buildPdfBytes(data, verifyUrl);

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${receipt_id}.pdf"`,
      },
    });
  } catch (err) {
    console.error("[Receipt-PDF] Error:", err);
    return new Response(JSON.stringify({ error: "Internal server error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }
});
