import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import QRCode from "https://esm.sh/qrcode@1.5.4";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function buildPdfBytes(receipt: any, verifyUrl: string, qrDataUri: string): Uint8Array {
  const lines = [
    `APEX NOTARY — CRYPTOGRAPHIC ATTESTATION RECEIPT`,
    ``,
    `Receipt ID:        ${receipt.commit_id}`,
    `Timestamp:         ${receipt.created_at}`,
    `Predicate:         ${receipt.predicate_id}`,
    `Phase:             ${receipt.phase}`,
    `Status:            ${receipt.status}`,
    ``,
    `CRYPTOGRAPHIC PROOF`,
    `─────────────────────────────────────────────`,
    `Commit Hash:       ${receipt.commit_hash}`,
    `Merkle Leaf:       ${receipt.merkle_leaf_hash}`,
    `Merkle Root:       ${receipt.merkle_root || 'N/A'}`,
    `Ed25519 Signature: ${receipt.ed25519_signature || 'N/A'}`,
    `Sequence:          ${receipt.sequence_number || 'N/A'}`,
    ``,
    `ACTION`,
    `─────────────────────────────────────────────`,
    `${receipt.action}`,
    ``,
    `VERIFICATION`,
    `─────────────────────────────────────────────`,
    `Verify this receipt: ${verifyUrl}`,
    `Scan QR code below to verify independently.`,
    ``,
    `This receipt was cryptographically signed using Ed25519`,
    `(RFC 8032) and anchored to a SHA-256 Merkle tree per`,
    `PSI Protocol v1.2 (draft-singh-psi-00).`,
    ``,
    `EU AI Act Compliance: Articles 12, 13, 14`,
    `Algorithm: SHA-256 (FIPS 180-4)`,
    `Signature: Ed25519 (RFC 8032)`,
    ``,
    `Generated by APEX NOTARY — digital-gallows.com`,
  ];

  // Extract raw PNG bytes from data URI for QR code
  const base64Data = qrDataUri.split(",")[1] || "";
  const qrBinaryStr = atob(base64Data);
  const qrBytes = new Uint8Array(qrBinaryStr.length);
  for (let i = 0; i < qrBinaryStr.length; i++) {
    qrBytes[i] = qrBinaryStr.charCodeAt(i);
  }

  // Build PDF with embedded QR image
  const objects: string[] = [];
  let objCount = 0;
  const offsets: number[] = [];

  const addObj = (content: string) => {
    objCount++;
    objects.push(`${objCount} 0 obj\n${content}\nendobj\n`);
    return objCount;
  };

  // 1: Catalog
  addObj(`<< /Type /Catalog /Pages 2 0 R >>`);
  // 2: Pages
  addObj(`<< /Type /Pages /Kids [3 0 R] /Count 1 >>`);
  // 3: Page
  addObj(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> /XObject << /QR 6 0 R >> >> >>`);

  // 4: Content stream
  const escapedLines = lines.map(l => l.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)'));
  let streamContent = "BT\n/F1 9 Tf\n";
  let y = 750;
  for (const line of escapedLines) {
    if (y < 140) break;
    streamContent += `1 0 0 1 50 ${y} Tm\n(${line}) Tj\n`;
    y -= 14;
  }
  streamContent += "ET\n";
  // Draw QR code at bottom right
  streamContent += `q\n100 0 0 100 460 30 cm\n/QR Do\nQ\n`;
  const streamBytes = new TextEncoder().encode(streamContent);
  addObj(`<< /Length ${streamBytes.length} >>\nstream\n${streamContent}endstream`);

  // 5: Font
  addObj(`<< /Type /Font /Subtype /Type1 /BaseFont /Courier >>`);

  // 6: QR Image XObject
  // Use raw hex-encoded PNG in an Image XObject with FlateDecode won't work easily
  // Instead embed as a simple hex stream with ASCIIHexDecode
  const hexStream = Array.from(qrBytes).map(b => b.toString(16).padStart(2, '0')).join('');
  addObj(`<< /Type /XObject /Subtype /Image /Width 200 /Height 200 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /ASCIIHexDecode /Length ${hexStream.length + 1} >>\nstream\n${hexStream}>\nendstream`);

  // Build file
  let pdf = "%PDF-1.4\n";
  for (const obj of objects) {
    offsets.push(pdf.length);
    pdf += obj + "\n";
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objCount + 1}\n`;
  pdf += `0000000000 65535 f \n`;
  for (const off of offsets) {
    pdf += `${off.toString().padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objCount + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`;

  return new TextEncoder().encode(pdf);
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405, headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }

  try {
    const { receipt_id } = await req.json();
    if (!receipt_id) {
      return new Response(JSON.stringify({ error: "Missing receipt_id" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" }
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const { data, error } = await supabase
      .from("gallows_ledger")
      .select("*")
      .eq("commit_id", receipt_id)
      .single();

    if (error || !data) {
      return new Response(JSON.stringify({ error: "Receipt not found" }), {
        status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" }
      });
    }

    const verifyUrl = `https://digital-gallows.com/verify?hash=${data.commit_hash}`;

    // Generate QR code as data URI
    let qrDataUri: string;
    try {
      qrDataUri = await QRCode.toDataURL(verifyUrl, {
        width: 200,
        margin: 1,
        color: { dark: "#000000", light: "#ffffff" },
      });
    } catch {
      // Fallback: empty small PNG
      qrDataUri = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";
    }

    const pdfBytes = buildPdfBytes(data, verifyUrl, qrDataUri);

    return new Response(pdfBytes, {
      status: 200,
      headers: {
        ...corsHeaders,
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${receipt_id}.pdf"`,
      },
    });
  } catch (err) {
    console.error("[Receipt-PDF] Error:", err);
    return new Response(JSON.stringify({ error: "Internal server error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" }
    });
  }
});
