project_id = "qhtntebpcribjiwrdtdd"

[functions.send-contact-email]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.run-verification]
verify_jwt = false

[functions.compliance-api]
verify_jwt = false

[functions.verify-hash]
verify_jwt = false
